[project]
name = "loading"
version = "0.0.0"
description = "loading.py checks packages, generates data, analyzes it, and saves a graph."
authors = [
    {name = "Pi"}
]
requires-python = ">=3.13"
dependencies = [
    "pandas (>=3.0)",
    "numpy (>=2.5.3)",
    "matplotlib (>=3.11.2)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
